save
Signed-off-by: chipzoller <chipzoller@gmail.com>

diff --git a/.github/workflows/discover-versions.yaml b/.github/workflows/discover-versions.yaml
--- a/.github/workflows/discover-versions.yaml
+++ b/.github/workflows/discover-versions.yaml
@@ -1,10 +1,15 @@
 # Requires a secret called MY_TOKEN to be set in the repo with a GitHub token that has gist permissions for read and write.
+# Only one of IMAGE_REPO or HELM_REPO should be specified.
 name: discover-versions
 on:
   workflow_dispatch: {}
 env:
   # The image repository to use for discovering tags.
   IMAGE_REPO: gcr.io/kubecost1/cost-model
+  # The Helm repository to use for discovering new releases.
+  HELM_REPO: https://kubecost.github.io/cost-analyzer/
+  # The Helm chart name to use for discovering new releases.
+  HELM_CHART: cost-analyzer
   # The gist ID to use for storing the last discovered version.
   GIST: 5bb3e010e5817903768c381c017cfcb4
   # The gist file name to use for storing the last discovered version.
@@ -23,6 +28,12 @@ jobs:
       # Can also be used for Helm charts: helm search repo cost-analyzer -l -o json | jq -r .[].version | head -n1
       - name: Discover latest tag
         run: |
+          if [[ -n $IMAGE_REPO && -n $HELM_REPO ]]; then
+            echo "Both IMAGE_REPO and HELM_REPO are defined. This script expects one or the other. Failing."
+            exit 1
+          else
+            echo "Conflicting variable check passed. Continuing."
+          fi
           LATEST=$(oras repo tags $IMAGE_REPO | egrep '^prod-1.[0-9]+.[0-9]+$' | sort -t "." -k1,1n -k2,2n -k3,3n | tail -n1)
           if [ -z "$LATEST" ]; then
             echo "No production tags found for $IMAGE_REPO. Something is wrong. Failing."
