try
Signed-off-by: chipzoller <chipzoller@gmail.com>

diff --git a/.github/workflows/discover-versions.yaml b/.github/workflows/discover-versions.yaml
--- a/.github/workflows/discover-versions.yaml
+++ b/.github/workflows/discover-versions.yaml
@@ -8,7 +8,7 @@ env:
   # The image repository to use for discovering image tags. This is mutually exclusive with HELM_REPO.
   IMAGE_REPO: gcr.io/kubecost1/cost-model
   # The regex pattern to use when disovering image tags. This one matches the pattern "prod-1.x.x", not any pre-releases or other tags.
-  IMAGE_REGEX: '^prod-1.[0-9]+.[0-9]+$'
+  # IMAGE_REGEX: '^prod-1.[0-9]+.[0-9]+$'
   # The Helm repository to use for discovering new releases. This is mutually exclusive with IMAGE_REPO.
   # HELM_REPO: https://kubecost.github.io/cost-analyzer/
   # The Helm chart name to use for discovering new releases. This is required if HELM_REPO is set.
@@ -27,7 +27,7 @@ jobs:
       - name: Install oras CLI
         uses: oras-project/setup-oras@v1
       # Get the latest image tag or Helm chart version, whichever is specified.
-      # Only one of either IMAGE_REPO or HELM_REPO can be defined.
+      # Only one of either IMAGE_REPO or HELM_REPO may be defined.
       - name: Discover latest tag
         run: |
           if [[ -z $IMAGE_REPO && -z $HELM_REPO ]]; then
@@ -44,6 +44,10 @@ jobs:
           fi
           if [[ -n $IMAGE_REPO ]]; then
             echo "IMAGE_REPO is defined. Will use this to discover the latest tag."
+            if [[ -z $IMAGE_REGEX ]]; then
+              echo "IMAGE_REGEX is not defined. This is required when using IMAGE_REPO. Failing."
+              exit 1
+            fi
             LATEST=$(oras repo tags $IMAGE_REPO | egrep "$IMAGE_REGEX" | sort -t "." -k1,1n -k2,2n -k3,3n | tail -n1)
           else
             echo "HELM_REPO is defined. Will use this to discover the latest release."
